title: Speech to Music through Emotion
description: SeungHeon Doh, Minz Won, Keunwoo Choi, Juhan Nam

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/SeungHeonDoh/speech_to_music_demo
